export const nationalFoods = [
    {
        id:1,
        name:"Beshbarmak",
        img:'https://too.kg/en/wp-content/uploads/ac075a27ed4058fdd96fdcd0b45e8400-600x400.jpg',
        price:30
    },
    {
        id:2,
        name:"Borsok",
        img:'https://too.kg/en/wp-content/uploads/borsoki-600x400.jpg',
        price:20
    },
    {
        id:3,
        name:"Chuchuk",
        img:'https://too.kg/en/wp-content/uploads/chuchuk.jpg',
        price:24
    },
    {
        id:4,
        name:"Shorpo",
        img:'https://too.kg/en/wp-content/uploads/lojka34-600x400.jpg',
        price:15
    },
    {
        id:5,
        name:"Kurut",
        img:'https://too.kg/en/wp-content/uploads/ef86c2aaff7a1791ba47225cb036ab5b-800x800-600x400.jpg',
        price:'33'
    },
    {
        id:6,
        name:"Kuurdak",
        img:'https://too.kg/en/wp-content/uploads/kuurdak-600x360.jpg',
        price:'40'
    }
]